name: Check PR Source
on:
  pull_request:
    branches: [ prod ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch is dev
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Only 'dev' can be merged into 'prod'."
          exit 1
